### ISSUE TITLE
有关报错的问题 请您指教

### ISSUE THREAD

**Issue by Choitsugun** [shawnspace/HRAN#11]
我在跑代码时出现了报错 希望能得到您的帮助

在train模型的时候 先是出现如下报错↓

Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "/home2/cho/HRAN-master/train.py", line 121, in <module>
    tf.app.run()
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home2/cho/HRAN-master/train.py", line 14, in main
    train()
  File "/home2/cho/HRAN-master/train.py", line 32, in train
    loss,debug_tensors = HRAN.impl(features=input_features,mode=modekeys.TRAIN,hp=hp)
  File "/home2/cho/HRAN-master/HRAN.py", line 133, in impl
    initial_state=attn_cell.zero_state(batch_size, tf.float32),
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1369, in zero_state
    for attention_mechanism in self._attention_mechanisms),
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1288, in _item_or_tuple
    t = tuple(seq)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1369, in <genexpr>
    for attention_mechanism in self._attention_mechanisms),
AttributeError: 'ContextAttentionMechanism' object has no attribute 'initial_state'

我参考AttentionWrapper官方代码 在ContextAttentionMechanism中添加了以下代码问题得以解决

def initial_state(self, batch_size, dtype):
    """Creates the initial state values for the `AttentionWrapper` class.
    This is important for AttentionMechanisms that use the previous alignment
    to calculate the alignment at the next time step (e.g. monotonic attention).
    The default behavior is to return the same output as initial_alignments.
    Args:
      batch_size: `int32` scalar, the batch_size.
      dtype: The `dtype`.
    Returns:
      A structure of all-zero tensors with shapes as described by `state_size`.
    """
    return self.initial_alignments(batch_size, dtype)

但是又出现了下面的报错↓

Traceback (most recent call last):
  File "/home2/cho/HRAN-master/train.py", line 121, in <module>
    tf.app.run()
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home2/cho/HRAN-master/train.py", line 14, in main
    train()
  File "/home2/cho/HRAN-master/train.py", line 32, in train
    loss,debug_tensors = HRAN.impl(features=input_features,mode=modekeys.TRAIN,hp=hp)
  File "/home2/cho/HRAN-master/HRAN.py", line 135, in impl
    final_outputs, final_state, final_sequence_lengths = dynamic_decode(decoder=decoder,impute_finished=True,parallel_iterations=32,swap_memory=True)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 137, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1448, in call
    self._attention_layers[i] if self._attention_layers else None)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1054, in _compute_attention
    cell_output, state=attention_state)
TypeError: __call__() got an unexpected keyword argument 'state'

我把 def __call__(self, query, previous_alignments)换成def __call__(self, query, state) 该问题得以解决 但是又出现了以下报错↓

Traceback (most recent call last):
  File "/home2/cho/HRAN-master/train.py", line 121, in <module>
    tf.app.run()
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home2/cho/HRAN-master/train.py", line 14, in main
    train()
  File "/home2/cho/HRAN-master/train.py", line 32, in train
    loss,debug_tensors = HRAN.impl(features=input_features,mode=modekeys.TRAIN,hp=hp)
  File "/home2/cho/HRAN-master/HRAN.py", line 135, in impl
    final_outputs, final_state, final_sequence_lengths = dynamic_decode(decoder=decoder,impute_finished=True,parallel_iterations=32,swap_memory=True)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 137, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1448, in call
    self._attention_layers[i] if self._attention_layers else None)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1054, in _compute_attention
    cell_output, state=attention_state)
  File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 442, in __iter__
    "Tensor objects are only iterable when eager execution is "
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.

针对这个报错 查了很多 但是貌似都没什么关系。。。请问这个问题怎么解决？（还是由于我在之前的报错时处理不当造成的？）
希望得到您的帮助 谢谢！

**Comment by Choitsugun** [comment]
> 我在跑代码时出现了报错 希望能得到您的帮助
> 
> 在train模型的时候 先是出现如下报错↓
> 
> Instructions for updating:
> Use tf.cast instead.
> Traceback (most recent call last):
> File "/home2/cho/HRAN-master/train.py", line 121, in 
> tf.app.run()
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "/home2/cho/HRAN-master/train.py", line 14, in main
> train()
> File "/home2/cho/HRAN-master/train.py", line 32, in train
> loss,debug_tensors = HRAN.impl(features=input_features,mode=modekeys.TRAIN,hp=hp)
> File "/home2/cho/HRAN-master/HRAN.py", line 133, in impl
> initial_state=attn_cell.zero_state(batch_size, tf.float32),
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1369, in zero_state
> for attention_mechanism in self._attention_mechanisms),
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1288, in _item_or_tuple
> t = tuple(seq)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1369, in 
> for attention_mechanism in self._attention_mechanisms),
> AttributeError: 'ContextAttentionMechanism' object has no attribute 'initial_state'
> 
> 我参考AttentionWrapper官方代码 在ContextAttentionMechanism中添加了以下代码问题得以解决
> 
> def initial_state(self, batch_size, dtype):
> """Creates the initial state values for the `AttentionWrapper` class.
> This is important for AttentionMechanisms that use the previous alignment
> to calculate the alignment at the next time step (e.g. monotonic attention).
> The default behavior is to return the same output as initial_alignments.
> Args:
> batch_size: `int32` scalar, the batch_size.
> dtype: The `dtype`.
> Returns:
> A structure of all-zero tensors with shapes as described by `state_size`.
> """
> return self.initial_alignments(batch_size, dtype)
> 
> 但是又出现了下面的报错↓
> 
> Traceback (most recent call last):
> File "/home2/cho/HRAN-master/train.py", line 121, in 
> tf.app.run()
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "/home2/cho/HRAN-master/train.py", line 14, in main
> train()
> File "/home2/cho/HRAN-master/train.py", line 32, in train
> loss,debug_tensors = HRAN.impl(features=input_features,mode=modekeys.TRAIN,hp=hp)
> File "/home2/cho/HRAN-master/HRAN.py", line 135, in impl
> final_outputs, final_state, final_sequence_lengths = dynamic_decode(decoder=decoder,impute_finished=True,parallel_iterations=32,swap_memory=True)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
> swap_memory=swap_memory)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
> return_same_structure)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
> pred, body, original_loop_vars, loop_vars, shape_invariants)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
> body_result = body(*packed_vars_for_body)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
> decoder_finished) = decoder.step(time, inputs, state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 137, in step
> cell_outputs, cell_state = self._cell(inputs, state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in **call**
> return super(RNNCell, self).**call**(inputs, state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in **call**
> outputs = super(Layer, self).**call**(inputs, *args, **kwargs)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in **call**
> outputs = self.call(inputs, *args, **kwargs)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1448, in call
> self._attention_layers[i] if self._attention_layers else None)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1054, in _compute_attention
> cell_output, state=attention_state)
> TypeError: **call**() got an unexpected keyword argument 'state'
> 
> 我把 def **call**(self, query, previous_alignments)换成def **call**(self, query, state) 该问题得以解决 但是又出现了以下报错↓
> 
> Traceback (most recent call last):
> File "/home2/cho/HRAN-master/train.py", line 121, in 
> tf.app.run()
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "/home2/cho/HRAN-master/train.py", line 14, in main
> train()
> File "/home2/cho/HRAN-master/train.py", line 32, in train
> loss,debug_tensors = HRAN.impl(features=input_features,mode=modekeys.TRAIN,hp=hp)
> File "/home2/cho/HRAN-master/HRAN.py", line 135, in impl
> final_outputs, final_state, final_sequence_lengths = dynamic_decode(decoder=decoder,impute_finished=True,parallel_iterations=32,swap_memory=True)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
> swap_memory=swap_memory)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
> return_same_structure)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
> pred, body, original_loop_vars, loop_vars, shape_invariants)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
> body_result = body(*packed_vars_for_body)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
> decoder_finished) = decoder.step(time, inputs, state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 137, in step
> cell_outputs, cell_state = self._cell(inputs, state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in **call**
> return super(RNNCell, self).**call**(inputs, state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in **call**
> outputs = super(Layer, self).**call**(inputs, *args, **kwargs)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in **call**
> outputs = self.call(inputs, *args, **kwargs)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1448, in call
> self._attention_layers[i] if self._attention_layers else None)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1054, in _compute_attention
> cell_output, state=attention_state)
> File "/home/nak/cho/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 442, in **iter**
> "Tensor objects are only iterable when eager execution is "
> TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
> 
> 针对这个报错 查了很多 但是貌似都没什么关系。。。请问这个问题怎么解决？（还是由于我在之前的报错时处理不当造成的？）
> 希望得到您的帮助 谢谢！

以上报错均因为 tensorfollow版本太靠后（1.14）降低了本版后（1.4）上述问题解决。

**Comment by Choitsugun** [comment]
以上报错均因为 tensorfollow版本太靠后（1.14）降低了本版后（1.4）上述问题解决。
